# Generated by Django 3.0.7 on 2020-06-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20200607_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='car',
            new_name='user_car',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='car_number',
            new_name='user_car_number',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='car_year',
            new_name='user_car_year',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='first_name',
            new_name='user_first_name',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='last_name',
            new_name='user_last_name',
        ),
    ]
