# Generated by Django 3.0.7 on 2020-06-20 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20200621_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 21, 4, 17, 4, 288219), null=True, verbose_name='Дата создания'),
        ),
    ]
