# Generated by Django 3.0.7 on 2020-06-20 23:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0002_auto_20200617_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='join',
            options={'verbose_name': 'Попутчиков', 'verbose_name_plural': 'Попутчики'},
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='email',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='avatar',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='rides',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 21, 4, 4, 6, 387316), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
