# Generated by Django 3.0.7 on 2020-06-21 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20200621_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='luggage',
            field=models.BooleanField(default=False, verbose_name='Возможность принять посылку/груз'),
        ),
        migrations.AlterField(
            model_name='rides',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 21, 15, 7, 10, 640172), null=True, verbose_name='Дата создания'),
        ),
    ]
