# Generated by Django 3.0.7 on 2020-06-21 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20200621_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='false',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rides',
            name='true',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rides',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 21, 15, 21, 33, 612627), null=True, verbose_name='Дата создания'),
        ),
    ]
