# Generated by Django 3.0.7 on 2020-06-21 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20200621_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='luggage_price',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Цена за кг груза (с.)'),
        ),
        migrations.AlterField(
            model_name='rides',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 21, 20, 34, 7, 436725), null=True, verbose_name='Дата создания'),
        ),
    ]
