# Generated by Django 3.0.7 on 2020-06-21 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20200621_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rides',
            name='luggage',
        ),
        migrations.RemoveField(
            model_name='rides',
            name='luggage_price',
        ),
        migrations.AlterField(
            model_name='rides',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 21, 22, 41, 4, 600956), null=True, verbose_name='Дата создания'),
        ),
    ]
