# Generated by Django 3.0.7 on 2020-06-12 21:10

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 13, 2, 10, 1, 604184), null=True, verbose_name='Дата создания')),
                ('pick_up_location', models.CharField(max_length=120, verbose_name='Место сбора')),
                ('drop_location', models.CharField(max_length=120, verbose_name='Пункт назначения')),
                ('total_rides', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Количество пассажиров(мин=1, макс=10)')),
                ('date', models.DateField(verbose_name='Дата(гг-мм-дд)')),
                ('time', models.TimeField(null=True, verbose_name='Время(ч:м)')),
                ('price', models.CharField(default='', max_length=120, verbose_name='Цена (с.)')),
                ('car', models.CharField(default='', max_length=120, verbose_name='Марка авто')),
                ('car_number', models.CharField(default='', max_length=12, verbose_name='Номер машины (01 0000 GG)')),
                ('car_year_issue', models.CharField(default='', max_length=4, verbose_name='Год выпуска машины')),
                ('phone_number', models.CharField(default='', max_length=15, verbose_name='Номер телефона (используйте в начале код страны)')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель поездки')),
            ],
            options={
                'verbose_name': 'Поездку',
                'verbose_name_plural': 'Поездки',
            },
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_phone', models.CharField(default='', max_length=13, verbose_name='Номер телефона (используйте в начале код страны со знаком +)')),
                ('status', models.BooleanField(default=False, verbose_name='видимость')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_rides', to='rides.Rides', verbose_name='Пользователь')),
            ],
        ),
    ]
