# Generated by Django 3.0.5 on 2020-05-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_location', models.TextField()),
                ('drop_location', models.TextField()),
                ('total_rides', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
