# Generated by Django 3.0.7 on 2020-06-12 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 12, 20, 22, 42, 58334), null=True, verbose_name='Дата создания'),
        ),
    ]
