# Generated by Django 3.0.5 on 2020-06-03 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rides',
            options={'verbose_name': 'Поездку', 'verbose_name_plural': 'Поездки'},
        ),
        migrations.RemoveField(
            model_name='rides',
            name='time',
        ),
        migrations.AddField(
            model_name='rides',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель поездки'),
        ),
        migrations.AddField(
            model_name='rides',
            name='car',
            field=models.CharField(default='', max_length=120, verbose_name='Марка авто'),
        ),
        migrations.AddField(
            model_name='rides',
            name='car_number',
            field=models.CharField(default='', max_length=12, verbose_name='Номер машины (01 0000 GG)'),
        ),
        migrations.AddField(
            model_name='rides',
            name='car_year_issue',
            field=models.CharField(default='', max_length=4, verbose_name='Год выпуска машины'),
        ),
        migrations.AddField(
            model_name='rides',
            name='phone_number',
            field=models.CharField(default='+992-xxx-xxx-xxx', max_length=13, verbose_name='Номер телефона (используйте в начале код страны)'),
        ),
        migrations.AlterField(
            model_name='rides',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время (дд.мм.гг ч.м)'),
        ),
        migrations.AlterField(
            model_name='rides',
            name='drop_location',
            field=models.CharField(max_length=120, verbose_name='Пункт назначения'),
        ),
        migrations.AlterField(
            model_name='rides',
            name='pick_up_location',
            field=models.CharField(max_length=120, verbose_name='Место сбора'),
        ),
        migrations.AlterField(
            model_name='rides',
            name='total_rides',
            field=models.IntegerField(verbose_name='Количество пассажиров'),
        ),
    ]
