# Generated by Django 3.0.7 on 2020-06-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20200603_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='price',
            field=models.CharField(default='', max_length=120, verbose_name='Цена (с.)'),
        ),
    ]
