# Generated by Django 3.0.7 on 2020-06-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_rides_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='phone_number',
            field=models.CharField(default='', max_length=13, verbose_name='Номер телефона (используйте в начале код страны)'),
        ),
    ]
