# Generated by Django 3.0.7 on 2020-06-08 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_auto_20200608_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_rides', to='rides.Rides', verbose_name='Пользователь'),
        ),
    ]
