# Generated by Django 3.0.7 on 2020-06-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_join_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='date_crate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rides',
            name='time',
            field=models.TimeField(null=True, verbose_name='Время(ч:м)'),
        ),
        migrations.AlterField(
            model_name='rides',
            name='date',
            field=models.DateField(verbose_name='Дата(дд.мм.гг)'),
        ),
    ]
