# Generated by Django 3.0.7 on 2020-06-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0010_auto_20200612_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='date_crate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
