# Generated by Django 3.0.7 on 2020-06-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0013_auto_20200612_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rides',
            old_name='date_crate',
            new_name='date_create',
        ),
    ]
